version: '3.5'

services:

    literacy-api:
        container_name: literacy-api
        build:
            context: .
        restart: always
        ports:
            - "8083:8083"
        networks:
            - literacy-api-network
        depends_on:
            - db
        env_file:
            - .env

    db:
        container_name: postgres-literacy-api
        image: postgres:12.3
        restart: always
        ports:
            - "5432:5432"
        networks:
            - literacy-api-network
        volumes:
            - postgres-literacy-api:/data/postgres
        env_file:
            - .env
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: literacy
            PGDATA: /data/postgres

volumes:
    postgres-literacy-api:

networks: 
    literacy-api-network:
        driver: bridge

